# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2714e4e4a52f593f55900927ea5a7d5576bfe7f57bc1feb0f749c07903e92870dafe4347306c5607a093b5f420fff335292b3d096d4d13f8f70ce0139c12c4da

test:
  secret_key_base: 522e6cb14f3d54b952b508e38470f38a4c9879ee338cf09ef0e698913cf56d259951b4332903fb5834b3027312196724b59290be60e1a5623eace5edd32d954e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
